module.exports = [
	{
		men: [
			"men-tshirts",
			// "men-casual-shirts",
			// "men-formal-shirts",
			// "men-sweatshirts",
			// "men-sweaters",
			// "men-jackets",
			// "men-blazers",
			// "men-suits",
			// "rain-jacket",
			// "men-kurtas",
			// "sherwani",
			// "nehru-jackets",
			// "dhoti",
			// "men-jeans",
			// "men-casual-trousers",
			// "men-formal-trousers",
			// "mens-shorts",
			// "men-trackpants",
			// "men-innerwear",
			// "men-briefs-and-trunks",
			// "men-boxers",
			// "men-innerwear-vests",
			// "men-nightwear",
			// "men-thermals",
			// "men-casual-shoes",
			// "men-sports-shoes",
			// "men-formal-shoes",
			// "men-sneakers",
			// "men-sandals",
			// "men-flip-flops",
			// "men-socks",
			// "men-sports-wear",
			// "men-sports-shoes",
			// "men-sports-sandals",
			// "men-sports-wear-tshirts",
			// "men-trackpants-shorts",
			// "men-tracksuits",
			// "men-sports-jackets",
			// "men-sports-accessories",
			// "men-sunglasses",
			// "men-wallets",
			// "men-belts",
			// "perfumes",
			// "trimmer",
			// "deodorant",
			// "men-belts-ties",
			// "men-accessory-gift-set",
			// "men-caps",
		],
		women: [
			"women-kurtas-kurtis-suits",
			// "ethnic-tops",
			// "ethnic-wear-dresses-menu",
			// "women-ethnic-bottomwear",
			// "skirts-palazzos",
			// "saree",
			// "dress-material",
			// "lehenga-choli",
			// "dupatta-shawl",
			// "women-ethnic-wear-jackets",
			// "women-shirts-tops-tees",
			// "women-jeans-jeggings",
			// "women-trousers",
			// "women-shorts-skirts",
			// "women-shrugs",
			// "women-sweaters-sweatshirts",
			// "women-jackets-coats",
			// "women-blazers-waistcoats",
			// "flats",
			// "women-casual-shoes",
			// "women-heels",
			// "women-sports-shoes",
			// "women-sportswear-clothing",
			// "women-sports-shoes",
			// "women-sports-accessories",
			// "women-sports-equipments",
			// "bra",
			// "women-briefs",
			// "women-clothing-shapewear",
			// "women-loungewear-and-nightwear",
			// "women-swimwear",
			// "camisoles-and-thermals",
			// "makeup",
			// "skin-care",
			// "women-personal-care",
			// "lipstick",
			// "women-perfumes",
			// "smart-wearables",
			// "fashion-jewellery",
			// "fine-jewellery",
		],
	},
];

