module.exports = [
	{
		men: [
			"Sports Shoes men",
			"Casual Shoes men",
			"Slippers Flip Flops men",
			"Sneakers men",
			"socks men",
			"jacket men",
			"Sandals Floaters men",
			"Formal Shoes men",
			"Loafers men",
			"Ethnic Footwear men",
			"Shoe Combos men",
			"Shoe Accessories men",
			"T - Shirts Polos men",
			"Shirts men",
			"Jeans men",
			"Trousers Chinos men",
			"Innerwear Sleepwear men",
			"Sunglasses men",
			"Jackets men",
			"Sweatshirts men",
			"Sweater men",
			"Thermals men",
			"Wallets men",
			"Belts men",
			"Hats Caps men",
			"Card Holders men",
			"Keychains men",
			"Suspenders men",
			"Backpacks men",
			"Laptop Bags men",
			"Hiking Bags men",
			"Luggage Suitcases men",
			"Shaving Creams Gels men",
			"Perfumes men",
			"Deodorants men",
		],
		women: [
			"Sarees women",
			"Kurtas Kurtis women",
			"Salwar Suits women",
			"Lehengas women",
			"Saree Combo women",
			"Salwars Leggings women",
			"Blouses Petticoats women",
			"Dresses women",
			"Tops Tunics women",
			"T-Shirts women",
			"Shirts women",
			"Denims Trousers women",
			"Pants Palazzos women",
			"Innerwear women",
			"Nightwear women",
			"Sportswear women",
			"Sunglasses women",
			"Spectacle Frames women",
			"Contact Lenses women",
			"Heels women",
			"Flats Sandals women",
			"Slippers Flip Flops women",
			"Ballerinas women",
			"Casual Shoes women",
			"Sports Shoes women",
			"Ethnic Footwear women",
			"Floater Sandal women",
			"Outerwear Jackets women",
			"Sweatshirts women",
			"Cardigans Pullovers women",
			"Shrugs Waistcoats women",
			"Rings women",
			"Earrings women",
			"Silver Jewellery women",
			"Handbags women",
			"Wallets women",
			"Clutches women",
			"Utility bags women",
			"Perfumes women",
			"Deodorants women",
			"Hair Accessories women",
			"Stoles Scarves women",
			"Socks Stockings women",
		],
	},
];
