module.exports = [
  {
    men: [
      "Flip Flop men",
      "Kurta men",
      "Kurta sets men",
      "Casual Shoes men",
      "Sneakers men",
      "Formal Shoes men",
      "Running Shoes men",
      "Training Shoes men",
      "Sports Shoes men",
      "Boots men",
      "T-shirtss Polos men",
      "Casual Shirts men",
      "Jeans men",
      "Trouserss Chinos men",
      "Shorts men",
      "Sweat Shirts men",
      "Casual Jackets men",
      "Formal Shirts men",
      "Formal Trousers men",
      "T-shirtss Jerseys men",
      "Sports Jackets men",
      "Joggers men",
      "Trunks men",
      "Smart Watches men",
      "Workwear Watches men",
      "Casual Watches men",
      "Partywear Watches men",
      "Digital watches men",
      "Multifunctional watches men",
      "Backpacks men",
      "Wallets men",
      "Messenger Bags men",
      "Cross Body Bags men",
      "Trolleys Bagss Suitcases men",
      "Duffle Bags men",
      "Rucksacks Trekking Backpacks men",
      "Belts men",
      "Hatss Caps men",
      "Tiess Cufflinks men",
      "Men's Gift Sets",
    ],
    women: [
      "Kurtass Kurtis women",
      "Suit Sets women",
      "Sareess Lehenga sets women",
      "Bottoms women",
      "Dupattas women",
      "Blousess Dress material women",
      "Bras women",
      "Panties women",
      "Camisole women",
      "Sleepwears Robes women",
      "Shapewear women",
      "Tops Tees women",
      "Dresses women",
      "Shirts women",
      "Pants Trousers women",
      "Jeans women",
      "Leggings women",
      "Jumpsuits women",
      "Skirts women",
      "Jackets Blazers women",
      "Shrugs women",
      "Sweatshirts women",
      "Sweaters women",
      "Casual women",
      "Ethnic women",
      "Formal women",
      "Sneakers women",
      "Boots women",
      "Sports Shoes women",
      "Flip-Flops women",
      "Dressy Watches women",
      "Casual Watches women",
      "Smart Watches women",
      "Formal Watches women",
      "Sporty watches women",
      "Handbags women",
      "Tote Bags women",
      "Sling Bags women",
      "Laptop Bags women",
      "Backpacks women",
      "Wallets women",
      "Clutches women",
      "Leather Handbags women",
      "Cat Eye",
    ],
  },
];
